version: "2"
services:
  crew_db:
    image: postgres:9.6
    ports:
     - "5432:5432"
    env_file:
     - ../locale/env/crew_service
    volumes:
      - /home/veris/micro-services/crew/data/postgres:/var/lib/postgresql/data
  v_crew:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
     - ../locale/env/crew_service
    environment:
     DEBUG: 'true'
    command: bash -c "python ./manage.py migrate && python ./manage.py runserver 0.0.0.0:8015"
    volumes:
     - .:/v-crew
    ports:
     - "8015:8015"
#    depends_on:
#      - templates_db
